### ISSUE TITLE
ajax support doc

### ISSUE THREAD

**Issue by lodev09** [lodev09/bootstrap-suggest#13]
Need doc update on the gh page.

**Comment by craigweston** [comment]
I'll take a look at getting this added.

**Comment by lodev09** [comment]
@craigweston thanks man. I know the doc is crappy so bare with me. LOL

**Comment by craigweston** [comment]
@lodev09 I created a pull request [here](https://github.com/lodev09/bootstrap-suggest/pull/15) for this. Let me know what you think.

**Comment by lodev09** [comment]
Merged! Thanks @craigweston

**Comment by craigweston** [comment]
@lodev09 that escaping problem with &amp; and &lt; issue on the gh page seems to be an issue with the marked library being used.

See here: 
- [Issue 625](https://github.com/chjj/marked/issues/625)
- [Issue 287](https://github.com/chjj/marked/issues/287)

**Comment by lodev09** [comment]
yes I noticed that too.. I tried to edit/fix it but it didn't work so it seems like it's an issue with the plugin. I guess will have to wait for an update
