### ISSUE TITLE
No Support for Scolling

### ISSUE THREAD

**Issue by adamatyork** [lodev09/bootstrap-suggest#18]
Excellent plugin, really useful. I can't seem to get it working with a scrollbar. 
Would be good if you could set a max-height or max-visible-items for the suggest, and then scrollbar becomes available to view the other items.

**Comment by lodev09** [comment]
I think you can set the option `filter.limit` to something bigger then do your scrollbar thing via CSS.
```
$('#textarea').suggest('@', {
	data: myData,
	filter: { limit: 100 }
});
```
