### ISSUE TITLE
remove requirement on bootstrap

### ISSUE THREAD

**Issue by aaronorosen** [lodev09/bootstrap-suggest#19]
It would be nice if this didn't require bootstrap or carried around the optional css bits that are needed. This way this could be used in other places that aren't using bootstrap

**Comment by kavin-90** [comment]
just rip bootstrap dropdown it will work  :smile:

**Comment by aaronorosen** [comment]
Yea, that's what I did though you have to modify the dropdown file a little bit to import the variables file, etc. I guess this isn't that important so I'll close it.
