### ISSUE TITLE
Lazy load images

### ISSUE THREAD

**Issue by vhf** [lodev09/bootstrap-suggest#2]
Hi, and thank you for this excellent project.

Would it be possible to modify it to lazy load images, and if so how would you go about it? I'm ready to give it a try and open a PR.

In one of my projects I'm using it to insert emojis, but on page load my 1,000+ emojis are all loaded one by one, which is of course not ideal.

**Comment by lodev09** [comment]
how are you currently loading emojis? I'm using emojis too but I'm initializing the plugin on `focus` event of the `input/textarea` and using [emojify](https://github.com/hassankhan/emojify.js) plugin.

Anyway, feel free to submit your PR and I'll have a look. :)

**Comment by vhf** [comment]
I was using code that looks like this : 

        map: function (emoji) {
          if (emoji && emoji.hasOwnProperty('code') && emoji.hasOwnProperty('img')) {
            return {
              value: emoji.code,
              text: '<img height="20px;" src="static/'+emoji.img+'"> <small>:'+emoji.code+'</small>'
            };
          }
        },

And it tried to download them all at once on page load.

I change my code to make the onShow and onLookup populate the `src` field, thus loading emojis on demand instead of on page load.
