### ISSUE TITLE
Bug in code breaks support for multiple instances

### ISSUE THREAD

**Issue by walkerj77** [lodev09/bootstrap-suggest#22]
Line 575 of bootstrap-suggest.js should be:
`} else if (data && !(arg1 in data)) {`

otherwise adding a second instance of Suggest to an element won't work:

`$("#myTextarea").suggest("@",  {`
`       data: [{ username: "testuser", name: "Test User" }],`
`	map: function(user) {`
`		return {`
`			value: user.username,`
`			text: "<strong>" + user.name + "</strong>"`
`		}`
`	}`
`});`

`$("#myTextarea").suggest("#", {`
`    	data: [{ tag: "somehashtag", name: "Longer Hashtag Name" }],`
`    	map: function(hashtag) {`
`		return {`
`			value: hashtag.tag,`
`			text: "<strong>" + hashtag.name + "</strong>"`
`		}`
`	}`
`});`

**Comment by lodev09** [comment]
thanks @walkerj77
