### ISSUE TITLE
Outside resource (json file)

### ISSUE THREAD

**Issue by zera272** [lodev09/bootstrap-suggest#23]
Hi lodev09 , i want to use external resource for my mention feature
so i want to use like this
$('.mention-user').suggest('@', {
		  data: '/users.json',
		  map: function(user) {
		    return {
		      value: user.id,
		      text: '<strong>'+user.name+'</strong></small>'
		    }
		  }
		})
but nothing happen ,

**Comment by kavin-90** [comment]
you may like to use ajax.

```
$('#comment').suggest('@', {
  data: function(q) {
    if (q &amp;&amp; q.length &gt;= 3) {
      return $.getJSON("users/lookup.json", { q:q });
    }
  },
  map: function(user) {
    return {
      value: user.username,
      text: '<strong>'+user.username+'</strong> <small>'+user.fullname+'</small>'
    }
  }
})
```

**Comment by lodev09** [comment]
External resource is not "directly" supported as the `data` option only accepts `function` or `array`. If you don't like the idea of "real-time" ajax approach as @kavin-90 suggested, you can pre-load your data from your `/users.json`. Something like this:

```
$.get('/users.json', function(users) {
	$('.mention-user').suggest('@', {
		data: users,
		map: function(user) { ... }
	});
})
```
