### ISSUE TITLE
adding delay when hashtag

### ISSUE THREAD

**Issue by webfriend13** [lodev09/bootstrap-suggest#25]
Currently after typing #abcd, system will make 4 request to server side. 1 request for each character. I thought of using this function to add delay. 

```

function debounce(func, wait, immediate) {
    var timeout;
    return function() {
        var context = this,
            args = arguments;
        var later = function() {
            timeout = null;
            if (!immediate) func.apply(context, args);
        };
        var callNow = immediate && !timeout;
        clearTimeout(timeout);
        timeout = setTimeout(later, wait);
        if (callNow) func.apply(context, args);
    };
};
```
This is how I added the debounce function.
```
.suggest('#', {
       data:debounce(function(q){
                    if(q){
                            return $.post(url, {param:xyz})
                    }
        },700)
})
.map.......
```

With this I am successfully able to delay the calls to server by 700 millisecond. But the autocomplete list that shows up, does not come up. What is the best way to fix the issue.

**Comment by lodev09** [comment]
the `data` propery is expected to be filled with an data result from your `$.post`. Based on your code above, I don't see it returning the "data" from your `$.post`.

**Comment by webfriend13** [comment]
@lodev09 Thank you for quick reply. The above code works if I remove the debounce fucntion. I am returning data with the return statement.

**Comment by lodev09** [comment]
yeah but since you added your debounce, the `data` option won't get any. 
did you try to change this line?
```js
...
return func.apply(context, args);
...
```

**Comment by webfriend13** [comment]
I have not looked into it yet.  Can you please be more specific.

**Comment by webfriend13** [comment]
@lodev09 : Thank you for your help. I am confused. I need to change` func.apply(context, args);` into what ? Can you please share provide some more information.

**Comment by lodev09** [comment]
Hmmm, I feel like you're solution is not the proper so I'll add a "delay" option later :)

**Comment by webfriend13** [comment]
Any tentative date for releasing this change??

**Comment by lodev09** [comment]
@webfriend13 I've done some stuff to accommodate your request. Check this code:
```javascript
var timeout = null;

$("#myTextarea").suggest("@", {
  data: function(q, lookup) {
    var processData = function() {
      $.get('https://yoururl.com/get/something', function(data) {
        lookup(data);
      });
    };

    if (timeout) {
      clearTimeout(timeout);
      timeout = null;
    }

    if (q.length > 0) timeout = setTimeout(processData, 700);
  },
  map: function(user) {
    return {
      value: user.username,
      text: "<strong>" + user.name + "</strong>"
    }
  }
});
```

see updated [api here](http://lodev09.github.io/bootstrap-suggest/#api)
haven't had time to test this fully, let me know if you found issues :)

**Comment by lodev09** [comment]
Revisiting this again and I just realized this can be done via [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) as well :)

(I will not revert any code done to accommodate this)
