### ISSUE TITLE
Showing suggestion on priority

### ISSUE THREAD

**Issue by ahshawn** [lodev09/bootstrap-suggest#27]
Hello, I have 2 ways to show the suggestion to the user using categorization and some data in the list consist of parent and the children category and some don't have a parent which means they are the parent category themselves.

Example data:

`[{
val: "fastfoodrestaurant",
meta: "Fast Food Restaurant"
},
{
val: "macdonald",
meta: "Macdonald",
parent: "Fast Food Restaurant"
},
{
val: "kfc",
meta: "Kentucky Fried Chicken",
parent: "Fast Food Restaurant"
}
]`

This is my partial settings
`
    $('#input').suggest('#', {
      data: function(q) {
        return Categories.en;
      },
      map: function(cat) {
        return {
          value: cat.val,
          text: function() {
            if (cat.parent) {
              return (
                '<strong>#' +
                cat.meta +
                '  </strong>in<strong><em><small> ' +
                cat.parent +
                '</small></em></strong>'
              );
            } else {
              return '<strong>#' + cat.meta + '</strong>';
            }
          }
        };
      },
      filter: {
        casesensitive: false,
        limit: 6
      }`

when I type #Fast in the input field,
it shows me the autocomplete list like stated:
KFC in Fast Food Restaurant
Fast Food Restaurant
Macdonald in Fast Food Restaurant

Is there a way to prioritize the parent when first 3 letter match such as #fas and put Fast Food restaurant as the first item on the list?

**Comment by lodev09** [comment]
This is not yet possible. Your situation is a bit complicated for a simple plugin like this. Though I can add an option to let you provide your own function to filter and sort the results as you like but I'm not sure if that will be enough to fit your needs. Feel free to fork and modify it and submit a PR. I'll be happy to review it.

It looks like you're asking about "ranks" in your search which could be challenging for jquery. `$.grep` and `Array.sort` might work for you.

**Comment by ahshawn** [comment]
From what I know is that when we use #keywords, it's returning me the list as a dropdown list, if possible, I believe that there's a way to pipe the data before showing the data to the user, I will try to filter out the data.

**Comment by lodev09** [comment]
Yes from text and sorting is based on your data source array. I'm afraid I cannot help you with your issue.

If you're data is coming from a database, you might want to consider providing a remote data source and filter it in server side (ajax). See [api docs](http://lodev09.github.io/bootstrap-suggest/#via-promise-or-ajax)

**Comment by ahshawn** [comment]
Yes, I have read that, however, even if I process that on the backend server, is the dropdownlist show the data in sequence? like from top to bottom, if yes, I am able to implement a workaround.

**Comment by ahshawn** [comment]
I have managed to sort it successfully to what I desire and I think you should update the docs that the data is displayed in sequence. Thanks for the information.
