### ISSUE TITLE
Delete items

### ISSUE THREAD

**Issue by albertShake** [lodev09/bootstrap-suggest#28]
Is there any way to know which item is removed from the text area?, like select2 works, using an unselect event.

Remove items from the dropdown when they have already been entered in the text area

**Comment by lodev09** [comment]
not yet sorry.. Note that you can pass `function` to the `data` option so it's easy for you to control the data you pass to the plugin. Example here:
http://lodev09.github.io/bootstrap-suggest/#via-promise-or-ajax
