### ISSUE TITLE
Ajax Supported?

### ISSUE THREAD

**Issue by rajlaksh** [lodev09/bootstrap-suggest#3]
is Ajax Supported?

I want to fetch result from AJAX how to do it with this Plugin?

This is My JSON data
`[{"user_name":"admin","full_name":"Admin"},{"user_name":"admin1","full_name":"admin1"},{"user_name":"admin2","full_name":"admin2"}]`

My JS Code
`$('textarea').suggest('@', {
data: $.post('/ajax/suggest',function(e){
return e;
}),
,
map: function(user) {
    return {
      value: user.user_name,
      text: '<strong>'+user.user_name+'</strong> '
    }
  }
});`

**Comment by lodev09** [comment]
The plugin does not support **real time** when you search but I'm open for a PR :)

Anyway, you can put the initialization inside the ajax callback like this:
```javascript
$.post('/ajax/suggest', function(jsonData) {
	$('textarea').suggest('@', {
		data: jsonData,
		map: function(user) {
			return { value: user.user_name, text: '<strong>'+user.user_name+'</strong> ' }
		}
	});
});
```

**Comment by rajlaksh** [comment]
Thanks for Code.

**Comment by lodev09** [comment]
nope not yet.. I'm still working on that. but I'm open for PR

**Comment by rajlaksh** [comment]
@lodev09  PR?

**Comment by lodev09** [comment]
[pull request](https://help.github.com/articles/using-pull-requests/)

**Comment by rajlaksh** [comment]
okay thanks. I'm also trying to make it.

**Comment by rajlaksh** [comment]
You can check how Hawkers/triggeredAutocomplete done it 
https://github.com/Hawkers/triggeredAutocomplete/blob/master/jquery-ui.triggeredAutocomplete.js

**Comment by lodev09** [comment]
I'm not so sure if I will be able to do this feature in the plugin anytime soon since this will entirely change some core codes. Basically, I'm pre-rendering the `dropdown` layout from the initial data and using the `hidden` class to toggle visible items when searching.

I'll leave this issue open incase I may have time to work on this :)

**Comment by rajlaksh** [comment]
Thanks. Take your Time :)
