### ISSUE TITLE
Support to update the items list once the element has been bind !!

### ISSUE THREAD

**Issue by vedbhawsar** [lodev09/bootstrap-suggest#35]
Is there any way exists that we can update the itemlist (add a new item) after we have bind the element using suggest()?

**Comment by lodev09** [comment]
You can either reinitialized or add it on-the-fly like so:
```js
var data = $('#comment').data('suggest');
data['@'].options.data.push({username: 'test', fullname: 'New name'});
```
_Note: code above assumes that the `data` option is an array._
