### ISSUE TITLE
Cannot read property create range of undefined

### ISSUE THREAD

**Issue by NicolasPerl** [lodev09/bootstrap-suggest#37]
I've been using this repo in production for a while. I noticed this error yesterday and after doing some dissecting myself I can't seem to find the issue.

Below is the code I'm using:

`$('.comment').suggest('#', {
                  data: postIDReverse,
                  map: function(id) {
                    return {
                      value: id, //id.value
                      text: '<strong>'+id+'</strong>' //id.value
                    }
                  }
   })`

'postIDReverse' corresponds to an array ["post35", "post34", "post33", "post31", "post30", "post28", "post26", "post25", "post24", "post23", "post22", "post21", "post20", "post19", "post18", "post17", "post16", "post15", "post14", "post13", "post12", "post11", "post10", "post9", "post8", "post7", "post6", "post5", "post4", "post3", "post2", "post1"]

The error I'm getting is from bootstrap-suggest.js. I provided a screenshot of the error. 

Please let me know if you need any more information. I've been looking into this for a few hours, so I hope I'm not missing something simple. 

Any guidance helps!

<img width="665" alt="screen shot 2019-02-15 at 2 26 01 pm" src="https://user-images.githubusercontent.com/12616774/52882554-b0bd5c00-312d-11e9-886b-b71307947844.png">

**Comment by lodev09** [comment]
quick google and it looks like the `document.selection` is already deprecated.
https://stackoverflow.com/a/19756936/3685987

**Comment by NicolasPerl** [comment]
Thanks for your quick response. So I stumbled upon that StackOverflow post yesterday and looked into it a bit, but went down a rabbit hole. After looking more into it I tweaked 
`range = document.selection.createRange();` to `range = document.createRange();` and I'm getting an output in the console.

Now it's throwing an error with parentElement(). I attached it below:

<img width="668" alt="screen shot 2019-02-15 at 3 10 11 pm" src="https://user-images.githubusercontent.com/12616774/52887955-6349ea80-313f-11e9-9547-3fb6e452bfd4.png">

I'll be looking into this, but if you find a fix let me know.

**Comment by lodev09** [comment]
@NicolasPerl what browser are you using? I can't replicate it cause that code block is suppose to be a workaround if `el.selectionStart` isn't available (not supported).

**Comment by lodev09** [comment]
would also help if you can provide a jsfiddle so I can see the code you're using.

**Comment by NicolasPerl** [comment]
The error is due to using the rich text editor - quill. It looks like the best way for me to have this mention functionality is to use another package. 

If anybody stumbles upon this error and needs a fix I'll be using this.

Thanks for your help @lodev09.

https://www.npmjs.com/package/quill-mention

**Comment by lodev09** [comment]
ahh well that make sense. this package does not support `contenteditable`. You can use [At.js](https://github.com/ichord/At.js) instead :)
