### ISSUE TITLE
Plugin support in emojionearea

### ISSUE THREAD

**Issue by MaksimDzhangirov** [lodev09/bootstrap-suggest#40]
First of all, thank you for plugin. I have a question. Can I use your plugin with [emojionearea](https://github.com/mervick/emojionearea)?

**Comment by lodev09** [comment]
@MaksimDzhangirov unfortunately emojionearea is it's own plugin so I guess you can but I would suggest you implement your own emoji dropdown using bootstrap-suggest. I've done this before using the [emojify](https://github.com/emojione/emojify.js) library.
