### ISSUE TITLE
Results display incorrectly when multiple AJAX calls are fired

### ISSUE THREAD

**Issue by MCEmperor** [lodev09/bootstrap-suggest#49]
I have created a simple suggestion box, using this code:

    $('#someElement').suggest('@', {
        data: function(q) {
            if (q) {
                return $.getJSON("some-url", { q: q });
            }
    });

This works in general. However, if another character is typed before the AJAX request returns, then the data is displayed incorrectly. In my case, only the values which occur in _both_ requests are displayed.

This issue could be addressed by `abort()`ing any pending XHR.

**Comment by lodev09** [comment]
@MCEmperor try this example:
http://lodev09.github.io/bootstrap-suggest/#add-delay-search-while-typing

You can do whatever you need inside the method before you return the data i.e. calling abort if you determine that user is still typing

**Comment by MCEmperor** [comment]
@lodev09 It can be done like this

    xhr = null;
    $('some-element').suggest('@', {
        data: function(q, lookup) {
            if (q) {
                if (xhr) {
                    xhr.abort();
                }
                xhr = $.getJSON("some-url", { q: q }, function(data) {
                    lookup(data);
                });
            }
        }
    })

but I think it would be nice to integrate this check into this plugin.
