### ISSUE TITLE
Question: suggestion without a specific key

### ISSUE THREAD

**Issue by marcohofmann** [lodev09/bootstrap-suggest#5]
hey lodev09, first of all: thanks for your work! really great plugin...

is it possible to tigger a suggest with just typing a letter? like on typeahead...
this would make your plugin perfect for a tag input.

thanks!

**Comment by rajlaksh** [comment]
for tag # will be good.

**Comment by lodev09** [comment]
Unfortunately, you need to specify the character you want the dropdown to trigger. this is the core of the plugin and changing it like an autocomplete style would really change how the plugin works.

**Comment by lodev09** [comment]
@rajlaksh you can specify **#** as the trigger like so:
```javascript
$('#comment').suggest('#', {
  data: users,
  map: function(user) {
    return {
      value: user.username,
      text: '<strong>'+user.username+'</strong> <small>'+user.fullname+'</small>'
    }
  }
})
```
Refer to the plugin [api](http://lodev09.github.io/bootstrap-suggest/#api) for more information :)

**Comment by marcohofmann** [comment]
ok, thx.

**Comment by rajlaksh** [comment]
@lodev09 that what i said in # will be good is refer to suggest('#' :smile:
