### ISSUE TITLE
Sensitivity

### ISSUE THREAD

**Issue by mkddostro** [lodev09/bootstrap-suggest#54]
Hey,
I didn't know where to put suggestions (the link on the project site for "feedback" didn't lead me anywhere to leave feedback honestly, or I am blind) so I'm putting it here.
I am using this plugin now and it works great. The only thing I am missing is a better sensitivity. There is an old plugin that did a great job at filtering/sorting results based on the input:
https://github.com/jakiestfu/Mention.js#sensitivity

This worked much better in terms of ordering the results. Maybe your plugin can do this already but I couldn't find any option for it. Without it, I am left with either correct input (case sensitive) which isn't very practicable with names or no ordering of the results ("A" will return every name that contains an "a" or "A" but doesn't weigh the results).

If you don't think this would be a great addition, never mind :)

**Comment by lodev09** [comment]
You can use the `filter.casesensitve` [option](https://github.com/lodev09/bootstrap-suggest/blob/7c308375b74d52974f800c72650ba8cf7d8ce9a0/src/bootstrap-suggest.js#L579)

**Comment by mkddostro** [comment]
I can but as I said, it does not help a lot.
You either set it to insensitive: everything will be suggested that works with the input string.
Or you set it to sensitive: only case matching strings will be suggested.
The idea of the sensitivity is the probable order of results being returned, taking the case and position of characters into account.
Case sensitivity doesn't solve this with true and false values.
When working with usernames you don't want to force anyone to use correct upper and lower case when looking up users but you also want results that look more matching to be on top of the suggestions list.
But since you haven't read the doc which was directly linked to the section that explains it I will just go for a modification myself.

**Comment by lodev09** [comment]
You're right, my bad, I directly concluded that you meant about case sensitivity. Anyways, feel free to submit a PR or lemme know how it goes for you.
