### ISSUE TITLE
Multiple Suggets on Textarea

### ISSUE THREAD

**Issue by rajlaksh** [lodev09/bootstrap-suggest#7]
I've a Textarea it has 2 Suggest. but only 1 work.

How to fix it? Any Suggestion

**Comment by lodev09** [comment]
can you paste here what you have so far?

**Comment by rajlaksh** [comment]
`// Suggest People`
`$.getJSON(base_url + '/ajax/suggest',function(jsonData) {
`$('textarea').suggest('@', {
`data: jsonData,
`map: function(user) {
`return { value: user.user_name, text: '<strong>'+user.user_name+'</strong> <small>'+user.full_name+'</small>' }
`},
`filter: { casesensitive: true }
`});
`});

`// Emoji `

`$.getJSON(base_url + '/ajax/emoji', function(jsonData) {`
`$('#twitter-post').suggest(':', {`
`data: jsonData,`
`map: function(emoji) {`
`return { value: emoji.value, text: '<span class="twa twa-lg twa_'+emoji.code+'"></span> <strong>'+emoji.text+'</strong> ' }`
`},`
`filter: { casesensitive: true }`
`});`
`});`

**Comment by lodev09** [comment]
that should work as I see it unless `#twitter-post` is not `textarea`. Anyway, you could do it like this to initiate both of them at once:

```javascript
var suggestData = {};

$.getJSON(url, function(jsonData) {
    suggestData['@'] = {
        data: jsonData,
        map: function(user) {
            return { value: user.user_name, text: '<strong>'+user.user_name+'</strong><small>'+user.full_name+'</small>' }
        }
    };
});

$.getJSON(emojiUrl, function(jsonData) {
    suggestData[':'] = {
        data: jsonData,
        map: function(emoji) {
            return { value: emoji.value, text: '<span class="twa twa-lg twa_'+emoji.code+'"></span> <strong>'+emoji.text+'</strong> ' }
        }
    }
});

$('#twitter-post').on('focus', function() {
    $(this).suggest(suggestData);
})
```

**Comment by rajlaksh** [comment]
thanks. 
#twitter-post is id of textarea

**Comment by lodev09** [comment]
can you setup a fiddle for your current code? That may help

**Comment by rajlaksh** [comment]
yes, but that didn't work only 1st @ work.

**Comment by rajlaksh** [comment]
Sorry, Now it works :smile:  Thanks :+1:

**Comment by heidarymr** [comment]
i add this line to code:
  var url = 'http://127.0.0.1/data.txt';

and copy this text to data.txt:

{"employees":[
    {"user_name":"John", "full_name":"Doe"},
    {"user_name":"Anna", "full_name":"Smith"},
    {"user_name":"Peter", "full_name":"Jones"}
]}


but my script doesn't work!

**Comment by lodev09** [comment]
how are you doing it? a js fiddle would help

**Comment by kavin-90** [comment]
@lodev09 how to use it will Ajax Options which is supported now?

should i use `suggestData[':'] = { },suggestData['@'] = { }`
