### ISSUE TITLE
Multiple Suggets Phrase

### ISSUE THREAD

**Issue by heidarymr** [lodev09/bootstrap-suggest#8]
i  have a text-area and want to define Multiple suggest phrase.
for example when a user type **'invoice:'** this plugin should be activate and when user type **'customer:'** this plugin should be activate from another source data
all of them should be activate in same text-area
can u have a solution for this?

**Comment by lodev09** [comment]
The plugin supports multiple suggest in one element but it does not support multiple character trigger. #7 has a sample on how you can achieve multiple suggest

**Comment by heidarymr** [comment]
is there any way to add 'multiple character trigger' feature to this script?

**Comment by lodev09** [comment]
yes.. see #7 there is an example there on how you can achieve this

**Comment by lodev09** [comment]
unfortunately no. it only supports **single** character trigger i.e. _@_
